"""US-048 / US-050 helper — emit the three diagnostic LaTeX tables.

Sources:
  - artifacts/validation/test_set_results.json (US-045 a) -> test_set_confirmation_table.tex
  - artifacts/figures/confusion/_index.json (US-045 b)    -> confusion_summary_table.tex
  - artifacts/figures/inference_throughput.csv (US-045 d) -> throughput_table.tex

These are the auto-generated LaTeX snippets referenced by
\input{...} inside docs/Final_Report.tex §XI and §XII.

Idempotency: re-runnable; reads the upstream JSONs/CSVs each time.
"""
from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AUTOGEN = ROOT / "docs" / "_autogen"

TEST_SET_JSON = ROOT / "artifacts" / "validation" / "test_set_results.json"
CONF_INDEX = ROOT / "artifacts" / "figures" / "confusion" / "_index.json"
THRPT_CSV = ROOT / "artifacts" / "figures" / "inference_throughput.csv"

OUT_TEST_SET = AUTOGEN / "test_set_confirmation_table.tex"
OUT_CONF = AUTOGEN / "confusion_summary_table.tex"
OUT_THRPT = AUTOGEN / "throughput_table.tex"

MODEL_LABEL = {"resnet50": "ResNet50", "densenet121": "DenseNet121", "transnext_tiny": "TransNeXt-tiny"}
DATASET_LABEL = {"cifar10": "CIFAR-10", "mnist": "MNIST"}
PHASE_ORDER = {"B": 0, "D": 1, "B2": 2, "B2nr": 3}
PHASE_LABEL = {"B": "B1", "D": "D-T3", "B2": "B2", "B2nr": "B2-nr"}


def _build_test_set_table() -> None:
    if not TEST_SET_JSON.exists():
        print(f"[skip] {TEST_SET_JSON} not present yet")
        return
    payload = json.loads(TEST_SET_JSON.read_text())
    entries = payload["entries"]
    # Aggregate: per (phase, model, dataset) -> mean test_acc + mean val_acc + mean gap
    agg: dict[tuple, list] = {}
    for e in entries:
        k = (e["phase"], e["model"], e["dataset"])
        agg.setdefault(k, []).append(e)

    lines = [
        r"% Auto-generated by scripts/build_diagnostics_latex.py - do not edit by hand",
        r"\begin{table}[t]",
        r"\centering\small",
        r"\caption{Held-out test-set confirmation at L3 Moderate. val\_acc is the canonical seed-42 value; test\_acc is the mean across seeds \{42, 43, 44\} on the stratified held-out test split (seed=99, $\sim$1000 samples per class). Gap is reported in percentage points.}",
        r"\label{tab:test_set_confirmation}",
        r"\begin{tabular}{ll l rrr}",
        r"\toprule",
        r"Model & Dataset & Phase & val\_acc (\%) & test\_acc (\%) & gap (pp) \\",
        r"\midrule",
    ]
    for k in sorted(agg, key=lambda kk: (PHASE_ORDER.get(kk[0], 99), kk[1], kk[2])):
        phase, m, d = k
        rows = agg[k]
        # canonical val_acc at seed=42
        c42 = next((r for r in rows if r["seed"] == 42), rows[0])
        val42 = c42["val_acc"] * 100
        # mean test_acc across all available seeds
        test_mean = sum(r["test_acc"] for r in rows) / len(rows) * 100
        gap_mean = test_mean - val42
        lines.append(
            f"{MODEL_LABEL[m]} & {DATASET_LABEL[d]} & {PHASE_LABEL.get(phase, phase)} & "
            f"{val42:.2f} & {test_mean:.2f} & {gap_mean:+.2f} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    OUT_TEST_SET.write_text("\n".join(lines))
    summary = payload["summary"]
    print(f"[test_set_table] wrote {OUT_TEST_SET}; max_abs_gap={summary['max_abs_gap_pp']:.2f}pp n_over_2pp={summary['n_gap_over_2pp']}")


def _build_confusion_table() -> None:
    if not CONF_INDEX.exists():
        print(f"[skip] {CONF_INDEX} not present yet")
        return
    payload = json.loads(CONF_INDEX.read_text())
    entries = payload["entries"]
    lines = [
        r"% Auto-generated by scripts/build_diagnostics_latex.py - do not edit by hand",
        r"\begin{table}[t]",
        r"\centering\small",
        r"\caption{L5 confusion-matrix summary (canonical seed=42). Top-confused pair lists the (true, predicted) class pair with the largest off-diagonal count.}",
        r"\label{tab:confusion_summary}",
        r"\begin{tabular}{ll l r l}",
        r"\toprule",
        r"Model & Dataset & Phase & L5 diag acc (\%) & Top-confused (true $\to$ predicted, count) \\",
        r"\midrule",
    ]
    entries_sorted = sorted(entries, key=lambda e: (PHASE_ORDER.get(e["phase"], 99), e["model"], e["dataset"]))
    for e in entries_sorted:
        mc = e["most_confused"]
        true_c = str(mc["true"]).replace("_", r"\_")
        pred_c = str(mc["predicted"]).replace("_", r"\_")
        lines.append(
            f"{MODEL_LABEL[e['model']]} & {DATASET_LABEL[e['dataset']]} & {PHASE_LABEL.get(e['phase'], e['phase'])} & "
            f"{e['val_acc_diag']*100:.2f} & {true_c} $\\to$ {pred_c} ({mc['count']}) \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    OUT_CONF.write_text("\n".join(lines))
    print(f"[confusion_table] wrote {OUT_CONF}; n_entries={len(entries)}")


def _build_throughput_table() -> None:
    if not THRPT_CSV.exists():
        print(f"[skip] {THRPT_CSV} not present yet")
        return
    rows = list(csv.DictReader(THRPT_CSV.open()))
    lines = [
        r"% Auto-generated by scripts/build_diagnostics_latex.py - do not edit by hand",
        r"\begin{table}[t]",
        r"\centering\small",
        r"\caption{Per-image inference throughput on RTX 5070 at 224$\times$224, batch size 1, bf16-mixed precision. Warmup 100 forward passes, measurement 1000 forward passes. CUDA event timing.}",
        r"\label{tab:throughput}",
        r"\begin{tabular}{l rrrrr}",
        r"\toprule",
        r"Model & Mean (ms) & Std (ms) & p50 (ms) & p95 (ms) & Throughput (img/s) \\",
        r"\midrule",
    ]
    for r in rows:
        lines.append(
            f"{MODEL_LABEL.get(r['model'], r['model'])} & "
            f"{float(r['mean_ms']):.2f} & {float(r['std_ms']):.2f} & "
            f"{float(r['p50_ms']):.2f} & {float(r['p95_ms']):.2f} & "
            f"{float(r['throughput_images_per_s']):.0f} \\\\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    OUT_THRPT.write_text("\n".join(lines))
    print(f"[throughput_table] wrote {OUT_THRPT}; n_models={len(rows)}")


def main() -> None:
    AUTOGEN.mkdir(parents=True, exist_ok=True)
    _build_test_set_table()
    _build_confusion_table()
    _build_throughput_table()


if __name__ == "__main__":
    main()
