"""US-048 — Phase C2 axis attribution plots.

For each (model, dataset) pair, plot val_acc vs L1..L5 for the 3 THz-protocol
axes (resolution / blur / salt_pepper) under C2 isolation, against the Phase A
clean baseline. Reveals which spatial-domain axis dominates Phase B2's drop.

Outputs:
  - artifacts/figures/phase_c2_attribution_<m>_<d>.png × 6
  - artifacts/figures/phase_c2_attribution_summary.png (2x3 composite)
  - docs/_autogen/phase_c2_attribution_table.tex
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Optional

import matplotlib
matplotlib.use("Agg")
matplotlib.rcParams["pdf.fonttype"] = 42
matplotlib.rcParams["svg.hashsalt"] = "phase_c2_attribute"
import matplotlib.pyplot as plt

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

RUNS = _REPO_ROOT / "runs" / "final"
OUT_DIR = _REPO_ROOT / "artifacts" / "figures"
AUTOGEN = _REPO_ROOT / "docs" / "_autogen"

MODELS = ("resnet50", "densenet121", "transnext_tiny")
DATASETS = ("cifar10", "mnist")
LEVELS = (1, 2, 3, 4, 5)
AXES = (
    ("resolution",  "#4c72b0", "o"),
    ("blur",        "#55a868", "s"),
    ("salt_pepper", "#c44e52", "^"),
)
MODEL_LABEL = {"resnet50": "ResNet50", "densenet121": "DenseNet121", "transnext_tiny": "TransNeXt-tiny"}
DATASET_LABEL = {"cifar10": "CIFAR-10", "mnist": "MNIST"}


def _va(tag: str) -> Optional[float]:
    p = RUNS / tag / "metrics.json"
    if not p.exists():
        return None
    return float(json.loads(p.read_text()).get("best_val_acc", float("nan")))


def _draw(ax, m: str, d: str) -> dict:
    row = {"model": m, "dataset": d}
    clean = _va(f"final_clean_{m}_{d}")
    if clean is not None:
        ax.axhline(clean * 100, color="black", linestyle="--", linewidth=0.9, alpha=0.7, label=f"A clean ({clean*100:.1f}%)")
        row["A_clean"] = clean
    for axis, color, marker in AXES:
        ys = [_va(f"final_C2_L{l}_{axis}_{m}_{d}") for l in LEVELS]
        vals = [(l, y * 100) for l, y in zip(LEVELS, ys) if y is not None]
        if vals:
            xv, yv = zip(*vals)
            ax.plot(xv, yv, color=color, marker=marker, linewidth=1.7, label=axis)
        for l, y in zip(LEVELS, ys):
            if y is not None:
                row[f"{axis}_L{l}"] = y
    ax.set_xticks(list(LEVELS))
    ax.set_xticklabels([f"L{l}" for l in LEVELS])
    ax.set_ylim(0, 100)
    ax.set_xlabel("Severity")
    ax.set_ylabel("Best val_acc (%)")
    ax.grid(True, alpha=0.3)
    ax.set_title(f"{MODEL_LABEL[m]} × {DATASET_LABEL[d]}", fontsize=11)
    ax.legend(loc="lower left", fontsize=8, framealpha=0.85)
    return row


def _save(fig, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=140, bbox_inches="tight", metadata={"CreationDate": None})
    pdf = path.with_suffix(".pdf")
    fig.savefig(pdf, bbox_inches="tight", metadata={"CreationDate": None})
    plt.close(fig)


def _emit_latex(rows: list[dict]) -> str:
    """Per-(m,d) per-axis L3 drop and 5-level mean drop."""
    lines = [
        r"% Auto-generated by scripts/plot_phase_c2_attribution.py - do not edit by hand",
        r"\begin{table}[t]",
        r"\centering\small",
        r"\caption{Phase C2 axis attribution: per-axis $\Delta_{\text{A}\to C2}$ at L3 and the 5-level mean. Negative values are drops from the Phase A clean baseline; the dominant axis under the THz protocol is shown in bold.}",
        r"\label{tab:phase_c2_attrib}",
        r"\begin{tabular}{ll rrr rrr}",
        r"\toprule",
        r" & & \multicolumn{3}{c}{L3 $\Delta$ (pp)} & \multicolumn{3}{c}{Mean L1..L5 $\Delta$ (pp)} \\",
        r"\cmidrule(lr){3-5}\cmidrule(lr){6-8}",
        r"Model & Dataset & resolution & blur & S\&P & resolution & blur & S\&P \\",
        r"\midrule",
    ]
    axis_keys = [a[0] for a in AXES]
    for r in rows:
        clean = r.get("A_clean")
        if clean is None:
            continue
        l3_deltas = []
        mean_deltas = []
        for axis in axis_keys:
            d3 = r.get(f"{axis}_L3")
            d_levels = [r.get(f"{axis}_L{l}") for l in LEVELS]
            l3_pp = (d3 - clean) * 100 if d3 is not None else None
            mean_pp_vals = [(v - clean) * 100 for v in d_levels if v is not None]
            mean_pp = (sum(mean_pp_vals) / len(mean_pp_vals)) if mean_pp_vals else None
            l3_deltas.append(l3_pp)
            mean_deltas.append(mean_pp)
        # Pick dominant (most negative) for L3
        valid_l3 = [(i, x) for i, x in enumerate(l3_deltas) if x is not None]
        dom_l3 = min(valid_l3, key=lambda kv: kv[1])[0] if valid_l3 else None
        valid_mean = [(i, x) for i, x in enumerate(mean_deltas) if x is not None]
        dom_mean = min(valid_mean, key=lambda kv: kv[1])[0] if valid_mean else None

        def _fmt(v, bold):
            if v is None:
                return "—"
            s = f"{v:+.2f}"
            return rf"\textbf{{{s}}}" if bold else s

        cells = []
        for i, v in enumerate(l3_deltas):
            cells.append(_fmt(v, i == dom_l3))
        for i, v in enumerate(mean_deltas):
            cells.append(_fmt(v, i == dom_mean))

        lines.append(
            f"{MODEL_LABEL[r['model']]} & {DATASET_LABEL[r['dataset']]} & " + " & ".join(cells) + r" \\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    return "\n".join(lines)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    AUTOGEN.mkdir(parents=True, exist_ok=True)

    rows: list[dict] = []
    fig, axes = plt.subplots(2, 3, figsize=(13.5, 7.2), dpi=140, sharey=True)
    for di, d in enumerate(DATASETS):
        for mi, m in enumerate(MODELS):
            ax = axes[di, mi]
            row = _draw(ax, m, d)
            rows.append(row)
            fig_p, ax_p = plt.subplots(figsize=(5.5, 3.7), dpi=140)
            _draw(ax_p, m, d)
            fig_p.tight_layout()
            _save(fig_p, OUT_DIR / f"phase_c2_attribution_{m}_{d}.png")

    fig.suptitle("Phase C2 axis attribution under the THz protocol (canonical seed=42)", fontsize=13)
    fig.tight_layout()
    _save(fig, OUT_DIR / "phase_c2_attribution_summary.png")

    tex = _emit_latex(rows)
    (AUTOGEN / "phase_c2_attribution_table.tex").write_text(tex)
    print(f"[plot_phase_c2] wrote {len(rows)} panels + LaTeX table")


if __name__ == "__main__":
    main()
