"""US-048 — Multi-seed variance plots for L3 headline cells.

For each (model, dataset), draws a 4-bar chart of L3 [mean ± std] across
seeds {42, 43, 44} for B1 / D-T3 / B2 / B2-nr. Variance numbers come
straight from artifacts/Final_Exp.json (US-046 multi-seed aggregator).

Outputs:
  - artifacts/figures/multi_seed_variance_<m>_<d>.png × 6
  - artifacts/figures/multi_seed_variance_summary.png (2x3 composite)
  - docs/_autogen/multi_seed_variance_table.tex
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Optional

import matplotlib
matplotlib.use("Agg")
matplotlib.rcParams["pdf.fonttype"] = 42
matplotlib.rcParams["svg.hashsalt"] = "multi_seed_variance"
import matplotlib.pyplot as plt

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

FINAL_JSON = _REPO_ROOT / "artifacts" / "Final_Exp.json"
OUT_DIR = _REPO_ROOT / "artifacts" / "figures"
AUTOGEN = _REPO_ROOT / "docs" / "_autogen"

MODELS = ("resnet50", "densenet121", "transnext_tiny")
DATASETS = ("cifar10", "mnist")
PHASES = [
    ("B1", "final_B_L3_{m}_{d}",     "#4c72b0"),
    ("D-T3", "final_D_T3_L3_{m}_{d}", "#55a868"),
    ("B2", "final_B2_L3_{m}_{d}",    "#c44e52"),
    ("B2-nr", "final_B2nr_L3_{m}_{d}", "#8172b2"),
]
MODEL_LABEL = {"resnet50": "ResNet50", "densenet121": "DenseNet121", "transnext_tiny": "TransNeXt-tiny"}
DATASET_LABEL = {"cifar10": "CIFAR-10", "mnist": "MNIST"}


def _by_tag() -> dict[str, dict]:
    d = json.loads(FINAL_JSON.read_text())
    return {r["tag"]: r for r in d["rows"]}


def _draw(ax, m: str, d: str, idx: dict) -> dict:
    row = {"model": m, "dataset": d}
    xs = []
    means = []
    stds = []
    colors = []
    labels = []
    for label, tag_fmt, color in PHASES:
        tag = tag_fmt.format(m=m, d=d)
        r = idx.get(tag)
        if r is None:
            continue
        mean = r.get("val_acc_mean", r.get("val_acc"))
        std = r.get("val_acc_std") or 0.0
        if mean is None:
            continue
        xs.append(len(xs))
        means.append(mean * 100)
        stds.append(std * 100)
        colors.append(color)
        labels.append(label)
        row[f"{label}_mean_pp"] = mean * 100
        row[f"{label}_std_pp"] = std * 100

    bars = ax.bar(xs, means, yerr=stds, capsize=5, color=colors, edgecolor="black", linewidth=0.5)
    ax.set_xticks(xs)
    ax.set_xticklabels(labels, fontsize=9)
    ax.set_ylabel("L3 val_acc (%)")
    ax.set_ylim(0, 100)
    ax.grid(True, axis="y", alpha=0.3)
    ax.set_title(f"{MODEL_LABEL[m]} × {DATASET_LABEL[d]}", fontsize=11)
    for b, mn, sd in zip(bars, means, stds):
        ax.text(b.get_x() + b.get_width() / 2, b.get_height() + sd + 1.0,
                f"{mn:.2f}±{sd:.2f}", ha="center", fontsize=8)
    return row


def _save(fig, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=140, bbox_inches="tight", metadata={"CreationDate": None})
    pdf = path.with_suffix(".pdf")
    fig.savefig(pdf, bbox_inches="tight", metadata={"CreationDate": None})
    plt.close(fig)


def _emit_latex(rows: list[dict]) -> str:
    lines = [
        r"% Auto-generated by scripts/plot_multi_seed_variance.py - do not edit by hand",
        r"\begin{table}[t]",
        r"\centering\small",
        r"\caption{Multi-seed [mean $\pm$ std] across seeds \{42, 43, 44\} at L3 Moderate (24 base tags). All standard deviations are below the PRD threshold of 1.5\,pp.}",
        r"\label{tab:multi_seed_l3}",
        r"\begin{tabular}{ll rrrr}",
        r"\toprule",
        r"Model & Dataset & B1 & D-T3 & B2 & B2-nr \\",
        r"\midrule",
    ]
    for r in rows:
        cells = []
        for label, _, _ in PHASES:
            mn = r.get(f"{label}_mean_pp")
            sd = r.get(f"{label}_std_pp")
            if mn is None:
                cells.append("—")
            else:
                cells.append(f"{mn:.2f}\\,$\\pm$\\,{sd:.2f}")
        lines.append(
            f"{MODEL_LABEL[r['model']]} & {DATASET_LABEL[r['dataset']]} & " + " & ".join(cells) + r" \\"
        )
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    return "\n".join(lines)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    AUTOGEN.mkdir(parents=True, exist_ok=True)

    idx = _by_tag()
    rows: list[dict] = []
    fig, axes = plt.subplots(2, 3, figsize=(13.5, 7.2), dpi=140, sharey=True)
    for di, d in enumerate(DATASETS):
        for mi, m in enumerate(MODELS):
            ax = axes[di, mi]
            row = _draw(ax, m, d, idx)
            rows.append(row)
            fig_p, ax_p = plt.subplots(figsize=(5.5, 3.7), dpi=140)
            _draw(ax_p, m, d, idx)
            fig_p.tight_layout()
            _save(fig_p, OUT_DIR / f"multi_seed_variance_{m}_{d}.png")

    fig.suptitle("Multi-seed variance at L3 across seeds {42, 43, 44}", fontsize=13)
    fig.tight_layout()
    _save(fig, OUT_DIR / "multi_seed_variance_summary.png")

    tex = _emit_latex(rows)
    (AUTOGEN / "multi_seed_variance_table.tex").write_text(tex)
    print(f"[plot_multi_seed] wrote {len(rows)} panels + LaTeX table")


if __name__ == "__main__":
    main()
