"""US-048 — Phase B2 comparison plots (4 series: B1 / D-T3 / B2 / B2-nr).

For each (model, dataset) pair:
  - Curve panel: val_acc vs degradation level L1..L5 with 4 series
    (B1, D-T3, B2 — full curves; B2-nr — single point at L3)
  - Per-panel PNG: artifacts/figures/phase_b2_comparison_<m>_<d>.png
Composite PNG (2x3 grid) at artifacts/figures/phase_b2_comparison_summary.png.
LaTeX table at docs/_autogen/phase_b2_comparison_table.tex with the
L3-anchored val_acc + Δ columns for the §VIII appendix.

Determinism: same matplotlib rc pins as plot_phase_d_comparison.py.
Idempotency: two consecutive runs produce byte-identical PNGs.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Optional

import matplotlib
matplotlib.use("Agg")
matplotlib.rcParams["pdf.fonttype"] = 42
matplotlib.rcParams["svg.hashsalt"] = "phase_b2_compare"
import matplotlib.pyplot as plt  # noqa: E402

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

RUNS = _REPO_ROOT / "runs" / "final"
OUT_DIR = _REPO_ROOT / "artifacts" / "figures"
AUTOGEN = _REPO_ROOT / "docs" / "_autogen"

MODELS = ("resnet50", "densenet121", "transnext_tiny")
DATASETS = ("cifar10", "mnist")
LEVELS = (1, 2, 3, 4, 5)
MODEL_LABEL = {"resnet50": "ResNet50", "densenet121": "DenseNet121", "transnext_tiny": "TransNeXt-tiny"}
DATASET_LABEL = {"cifar10": "CIFAR-10", "mnist": "MNIST"}

SERIES = [
    ("B1",    "B1",    "final_B_L{l}_{m}_{d}",     "#4c72b0", "o", "-"),
    ("D-T3",  "D-T3",  "final_D_T3_L{l}_{m}_{d}",  "#55a868", "s", "-"),
    ("B2",    "B2",    "final_B2_L{l}_{m}_{d}",    "#c44e52", "^", "-"),
    ("B2-nr", "B2-nr", "final_B2nr_L3_{m}_{d}",    "#8172b2", "D", ":"),  # L3-only
]


def _val_acc(tag: str) -> Optional[float]:
    p = RUNS / tag / "metrics.json"
    if not p.exists():
        return None
    return float(json.loads(p.read_text()).get("best_val_acc", float("nan")))


def _clean_acc(m: str, d: str) -> Optional[float]:
    p = RUNS / f"final_clean_{m}_{d}" / "metrics.json"
    if not p.exists():
        return None
    return float(json.loads(p.read_text()).get("best_val_acc", float("nan")))


def _draw_panel(ax, m: str, d: str) -> dict:
    """Draw the 4-series panel for one (m,d). Returns row dict for LaTeX."""
    row: dict = {"model": m, "dataset": d}
    xs = list(LEVELS)
    # Phase A clean baseline at L0
    clean = _clean_acc(m, d)
    if clean is not None:
        ax.scatter([0], [clean * 100], color="black", marker="*", s=80, zorder=5, label="A (clean)")
        row["A_clean"] = clean

    for short, label, tag_fmt, color, marker, ls in SERIES:
        if "_L3_" in tag_fmt and "{l}" not in tag_fmt:
            # B2-nr is a single point at L3
            tag = tag_fmt.format(m=m, d=d)
            v = _val_acc(tag)
            if v is None:
                continue
            ax.scatter([3], [v * 100], color=color, marker=marker, s=70, zorder=4, label=label)
            row[f"{short}_L3"] = v
        else:
            ys = [_val_acc(tag_fmt.format(l=l, m=m, d=d)) for l in LEVELS]
            valid = [(x, y * 100) for x, y in zip(xs, ys) if y is not None]
            if valid:
                vx, vy = zip(*valid)
                ax.plot(vx, vy, color=color, marker=marker, linewidth=1.6, linestyle=ls, label=label, zorder=3)
            for l, y in zip(LEVELS, ys):
                if y is not None:
                    row[f"{short}_L{l}"] = y

    ax.set_xticks([0, 1, 2, 3, 4, 5])
    ax.set_xticklabels(["A", "L1", "L2", "L3", "L4", "L5"])
    ax.set_ylim(0, 100)
    ax.set_ylabel("Best val_acc (%)")
    ax.grid(True, alpha=0.3)
    ax.set_title(f"{MODEL_LABEL[m]} × {DATASET_LABEL[d]}", fontsize=11)
    ax.legend(loc="lower left", fontsize=8, framealpha=0.85)
    return row


def _save(fig, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=140, bbox_inches="tight", metadata={"CreationDate": None})
    pdf = path.with_suffix(".pdf")
    fig.savefig(pdf, bbox_inches="tight", metadata={"CreationDate": None})
    plt.close(fig)


def _emit_latex(rows: list[dict]) -> str:
    """L3-anchored val_acc + Δ table for §VIII."""
    out = [
        r"% Auto-generated by scripts/plot_phase_b2_comparison.py - do not edit by hand",
        r"\begin{table}[t]",
        r"\centering\small",
        r"\caption{Phase B2 comparison at L3 Moderate. $\Delta_{\text{B1}\to X}$ is the per-cell improvement of phase $X$ over the Phase B1 baseline (positive = recovery toward clean accuracy).}",
        r"\label{tab:phase_b2_l3}",
        r"\begin{tabular}{ll rrrr rrr}",
        r"\toprule",
        r"Model & Dataset & B1 & D-T3 & B2 & B2-nr & $\Delta_{\text{B1}\to D\text{-}T3}$ & $\Delta_{\text{B1}\to B2}$ & $\Delta_{\text{B1}\to B2nr}$ \\",
        r"\midrule",
    ]
    for r in rows:
        b1 = r.get("B1_L3")
        dt3 = r.get("D-T3_L3")
        b2 = r.get("B2_L3")
        b2nr = r.get("B2-nr_L3")
        if any(v is None for v in (b1, dt3, b2, b2nr)):
            continue
        delta_dt3 = (dt3 - b1) * 100
        delta_b2 = (b2 - b1) * 100
        delta_b2nr = (b2nr - b1) * 100
        out.append(
            f"{MODEL_LABEL[r['model']]} & {DATASET_LABEL[r['dataset']]} & "
            f"{b1*100:.2f} & {dt3*100:.2f} & {b2*100:.2f} & {b2nr*100:.2f} & "
            f"{delta_dt3:+.2f} & {delta_b2:+.2f} & {delta_b2nr:+.2f} \\\\"
        )
    out.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}", ""])
    return "\n".join(out)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    AUTOGEN.mkdir(parents=True, exist_ok=True)

    rows: list[dict] = []
    # Per-panel + composite
    fig, axes = plt.subplots(2, 3, figsize=(13.5, 7.2), dpi=140, sharey=True)
    for di, d in enumerate(DATASETS):
        for mi, m in enumerate(MODELS):
            ax = axes[di, mi]
            row = _draw_panel(ax, m, d)
            rows.append(row)
            # Per-panel standalone
            fig_p, ax_p = plt.subplots(figsize=(5.5, 3.7), dpi=140)
            _draw_panel(ax_p, m, d)
            fig_p.tight_layout()
            _save(fig_p, OUT_DIR / f"phase_b2_comparison_{m}_{d}.png")

    fig.suptitle("Phase B2 comparison: B1 / D-T3 / B2 / B2-nr (canonical seed=42)", fontsize=13)
    fig.tight_layout()
    _save(fig, OUT_DIR / "phase_b2_comparison_summary.png")

    tex = _emit_latex(rows)
    (AUTOGEN / "phase_b2_comparison_table.tex").write_text(tex)
    print(f"[plot_phase_b2] wrote {len(rows)} panels + LaTeX table; composite={OUT_DIR/'phase_b2_comparison_summary.png'}")


if __name__ == "__main__":
    main()
