"""
Top N Best Runs Comparison Visualization

Creates a comparison plot showing the best performing experiments,
helping identify which models/approaches work best.
"""

from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from typing import Optional, List, Tuple


class TopRunsComparison:
    """Finds and visualizes the best performing runs."""

    def __init__(self, runs_dir: Path = Path("runs"), summary_csv: Path = Path("artifacts/tables/run_summary.csv")):
        """
        Initialize comparison visualizer.

        Args:
            runs_dir: Base directory containing all runs
            summary_csv: Path to run_summary.csv (generated by summarize_runs.py)
        """
        self.runs_dir = Path(runs_dir)
        self.summary_csv = Path(summary_csv)

    def get_top_runs(self, n: int = 3, exclude_incomplete: bool = True) -> List[dict]:
        """
        Find the top N runs by best_val_acc.

        Args:
            n: Number of top runs to return
            exclude_incomplete: Skip runs with missing best_val_acc

        Returns:
            List of dicts with run info, sorted by best_val_acc (descending)
        """
        if not self.summary_csv.exists():
            print(f"[ERROR] Summary CSV not found: {self.summary_csv}")
            print("[INFO] Run: python src/tools/summarize_runs.py")
            return []

        try:
            df = pd.read_csv(self.summary_csv)
        except Exception as e:
            print(f"[ERROR] Failed to read summary: {e}")
            return []

        # Filter out incomplete runs
        if exclude_incomplete:
            df = df.dropna(subset=['best_val_acc'])
            df = df[df['best_val_acc'] > 0]

        if len(df) == 0:
            print("[WARN] No complete runs found")
            return []

        # Sort by best_val_acc descending
        df = df.sort_values('best_val_acc', ascending=False)

        # Return top N
        top_runs = []
        for idx, row in df.head(n).iterrows():
            top_runs.append({
                'run_name': row['run_name'],
                'model_name': row['model_name'],
                'best_val_acc': row['best_val_acc'],
                'run_dir': Path(row['run_dir']) if 'run_dir' in row and pd.notna(row['run_dir']) else None,
                'low_res': row['low_res'] if 'low_res' in row else None,
            })

        return top_runs

    def load_run_metrics(self, run_dir: Path) -> Optional[pd.DataFrame]:
        """Load metrics CSV from a run directory."""
        metrics_file = run_dir / "metrics.csv"
        if not metrics_file.exists():
            return None

        try:
            return pd.read_csv(metrics_file)
        except:
            return None

    def plot_top_runs(self, n: int = 3, figsize: tuple = (16, 6), dpi: int = 100) -> Optional[Path]:
        """
        Create comparison plot of top N runs.

        Generates side-by-side plots:
        - Left: Validation accuracy curves for all top runs
        - Middle: Training accuracy curves for all top runs
        - Right: Loss curves for all top runs

        Args:
            n: Number of top runs to show
            figsize: Figure size (width, height)
            dpi: DPI for saved figure

        Returns:
            Path to saved figure
        """
        top_runs = self.get_top_runs(n)

        if not top_runs:
            print("[ERROR] No runs found to compare")
            return None

        print(f"\n[INFO] Found top {len(top_runs)} runs by best_val_acc:")
        for i, run in enumerate(top_runs, 1):
            acc = run['best_val_acc'] * 100 if run['best_val_acc'] else 0
            print(f"  {i}. {run['model_name']}: {acc:.2f}% ({run['run_name'][:50]}...)")

        # Create figure with 3 subplots
        fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=figsize, dpi=dpi)

        colors = ['#2E86AB', '#A23B72', '#F18F01']  # Blue, Purple, Orange
        markers = ['o', 's', '^']  # Circle, Square, Triangle

        # Collect all data for plotting
        max_epoch = 0

        for idx, run in enumerate(top_runs):
            if not run['run_dir']:
                continue

            metrics = self.load_run_metrics(run['run_dir'])
            if metrics is None or len(metrics) < 1:
                print(f"[WARN] Could not load metrics for {run['model_name']}")
                continue

            epochs = metrics['epoch'].values if 'epoch' in metrics.columns else range(len(metrics))
            max_epoch = max(max_epoch, max(epochs))

            label = f"{run['model_name']} ({run['best_val_acc']*100:.2f}%)"
            color = colors[idx % len(colors)]
            marker = markers[idx % len(markers)]

            # Plot 1: Validation Accuracy
            if 'val_acc' in metrics.columns:
                ax1.plot(epochs, metrics['val_acc'] * 100, marker=marker, color=color,
                        linewidth=2.5, markersize=6, label=label, alpha=0.8)
                # Mark best point
                best_idx = metrics['val_acc'].idxmax()
                best_acc = metrics['val_acc'].iloc[best_idx] * 100
                best_epoch = epochs[best_idx]
                ax1.plot(best_epoch, best_acc, marker='*', color=color, markersize=25)

            # Plot 2: Training Accuracy
            if 'train_acc' in metrics.columns:
                ax2.plot(epochs, metrics['train_acc'] * 100, marker=marker, color=color,
                        linewidth=2.5, markersize=6, label=label, alpha=0.8)

            # Plot 3: Validation Loss
            if 'val_loss' in metrics.columns:
                ax3.plot(epochs, metrics['val_loss'], marker=marker, color=color,
                        linewidth=2.5, markersize=6, label=label, alpha=0.8)

        # Configure Plot 1: Validation Accuracy
        ax1.set_xlabel('Epoch', fontsize=12, fontweight='bold')
        ax1.set_ylabel('Accuracy (%)', fontsize=12, fontweight='bold')
        ax1.set_title('Validation Accuracy - Top Runs', fontsize=13, fontweight='bold')
        ax1.set_ylim([0, 105])
        ax1.grid(True, alpha=0.3, linestyle='--')
        ax1.legend(loc='lower right', fontsize=10, framealpha=0.95)
        ax1.set_xlim([0, max_epoch + 1])

        # Configure Plot 2: Training Accuracy
        ax2.set_xlabel('Epoch', fontsize=12, fontweight='bold')
        ax2.set_ylabel('Accuracy (%)', fontsize=12, fontweight='bold')
        ax2.set_title('Training Accuracy - Top Runs', fontsize=13, fontweight='bold')
        ax2.set_ylim([0, 105])
        ax2.grid(True, alpha=0.3, linestyle='--')
        ax2.legend(loc='lower right', fontsize=10, framealpha=0.95)
        ax2.set_xlim([0, max_epoch + 1])

        # Configure Plot 3: Validation Loss
        ax3.set_xlabel('Epoch', fontsize=12, fontweight='bold')
        ax3.set_ylabel('Loss', fontsize=12, fontweight='bold')
        ax3.set_title('Validation Loss - Top Runs', fontsize=13, fontweight='bold')
        ax3.grid(True, alpha=0.3, linestyle='--')
        ax3.legend(loc='upper right', fontsize=10, framealpha=0.95)
        ax3.set_xlim([0, max_epoch + 1])

        # Overall title
        fig.suptitle(f'Top {len(top_runs)} Best Runs Comparison', fontsize=15, fontweight='bold')

        # Save
        output_path = Path("artifacts/figures/top_runs_comparison.png")
        output_path.parent.mkdir(parents=True, exist_ok=True)
        plt.tight_layout()
        plt.savefig(output_path, dpi=dpi, bbox_inches='tight')
        plt.close()

        print(f"\n[OK] Top runs comparison saved: {output_path}\n")
        return output_path

    def plot_best_vs_baselines(self, figsize: tuple = (14, 8), dpi: int = 100) -> Optional[Path]:
        """
        Create a summary visualization comparing best run against baselines.

        Shows a table-like visualization with key metrics.
        """
        top_runs = self.get_top_runs(3)

        if not top_runs:
            print("[ERROR] No runs found")
            return None

        fig, ax = plt.subplots(figsize=figsize, dpi=dpi)
        ax.axis('off')

        # Build summary text
        summary_lines = [
            "TOP 3 BEST RUNS - SUMMARY",
            "=" * 70,
            ""
        ]

        for i, run in enumerate(top_runs, 1):
            acc_pct = run['best_val_acc'] * 100 if run['best_val_acc'] else 0
            low_res_str = f"low_res={run['low_res']}" if run['low_res'] else "unknown"

            summary_lines.append(f"#{i}: {run['model_name']} - {acc_pct:.2f}% accuracy")
            summary_lines.append(f"    Run: {run['run_name'][:60]}")
            summary_lines.append(f"    Config: {low_res_str}")
            summary_lines.append("")

        summary_lines.extend([
            "=" * 70,
            "KEY FINDINGS:",
            f"- Best model: {top_runs[0]['model_name']} at {top_runs[0]['best_val_acc']*100:.2f}%",
        ])

        if len(top_runs) > 1:
            diff = (top_runs[0]['best_val_acc'] - top_runs[1]['best_val_acc']) * 100
            summary_lines.append(f"- {diff:.2f}% better than 2nd place")

        if len(top_runs) > 2:
            diff = (top_runs[0]['best_val_acc'] - top_runs[2]['best_val_acc']) * 100
            summary_lines.append(f"- {diff:.2f}% better than 3rd place")

        summary_text = "\n".join(summary_lines)

        ax.text(0.05, 0.95, summary_text, transform=ax.transAxes,
               fontsize=11, verticalalignment='top', fontfamily='monospace',
               bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.4))

        output_path = Path("artifacts/figures/top_runs_summary.png")
        output_path.parent.mkdir(parents=True, exist_ok=True)
        plt.savefig(output_path, dpi=dpi, bbox_inches='tight')
        plt.close()

        print(f"[OK] Top runs summary saved: {output_path}\n")
        return output_path


def plot_top_runs(n: int = 3) -> Optional[Path]:
    """Convenience function to generate top runs comparison."""
    comparator = TopRunsComparison()
    return comparator.plot_top_runs(n)


if __name__ == "__main__":
    import sys

    n = int(sys.argv[1]) if len(sys.argv) > 1 else 3

    comparator = TopRunsComparison()
    comparator.plot_top_runs(n)
    comparator.plot_best_vs_baselines()
